import { createHash } from 'node:crypto';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { verifyFixtureIntegrity } from '../runner/seed.js';

let tempDir: string;

beforeEach(async () => {
	tempDir = await mkdtemp(join(tmpdir(), 'regression-seed-'));
});
afterEach(async () => {
	await rm(tempDir, { recursive: true, force: true });
});

describe('verifyFixtureIntegrity', () => {
	it('returns ok when manifest matches actual file hashes', async () => {
		await writeFile(join(tempDir, 'a.png'), Buffer.from([1, 2, 3]));
		const expectedHash = createHash('sha256')
			.update(Buffer.from([1, 2, 3]))
			.digest('hex');
		const manifest = `${expectedHash}  a.png\n`;
		await writeFile(join(tempDir, 'a.sha256'), manifest);
		const result = await verifyFixtureIntegrity(join(tempDir, 'a.sha256'));
		expect(result.ok).toBe(true);
		expect(result.failures).toEqual([]);
	});

	it('detects tampered file (hash mismatch)', async () => {
		await writeFile(join(tempDir, 'a.png'), Buffer.from([1, 2, 3]));
		const wrongHash = 'a'.repeat(64);
		await writeFile(join(tempDir, 'a.sha256'), `${wrongHash}  a.png\n`);
		const result = await verifyFixtureIntegrity(join(tempDir, 'a.sha256'));
		expect(result.ok).toBe(false);
		expect(result.failures).toHaveLength(1);
		const [first] = result.failures;
		expect(first?.reason).toBe('mismatch');
		expect(first?.path).toBe('a.png');
	});

	it('detects missing file', async () => {
		await writeFile(join(tempDir, 'a.sha256'), `${'a'.repeat(64)}  missing.png\n`);
		const result = await verifyFixtureIntegrity(join(tempDir, 'a.sha256'));
		expect(result.ok).toBe(false);
		expect(result.failures).toHaveLength(1);
		const [first] = result.failures;
		expect(first?.reason).toBe('missing');
		expect(first?.path).toBe('missing.png');
	});

	it('rejects manifest line with traversal in path', async () => {
		await writeFile(join(tempDir, 'a.sha256'), `${'a'.repeat(64)}  ../../etc/passwd\n`);
		await expect(verifyFixtureIntegrity(join(tempDir, 'a.sha256'))).rejects.toThrow(/traversal/i);
	});

	it('rejects manifest line with absolute path', async () => {
		await writeFile(join(tempDir, 'a.sha256'), `${'a'.repeat(64)}  /etc/passwd\n`);
		await expect(verifyFixtureIntegrity(join(tempDir, 'a.sha256'))).rejects.toThrow(/absolute/i);
	});

	it('rejects malformed manifest line', async () => {
		await writeFile(join(tempDir, 'a.sha256'), 'not-a-hash  a.png\n');
		await expect(verifyFixtureIntegrity(join(tempDir, 'a.sha256'))).rejects.toThrow(/malformed/i);
	});

	it('skips blank lines and # comments', async () => {
		await writeFile(join(tempDir, 'a.png'), Buffer.from([1, 2, 3]));
		const expectedHash = createHash('sha256')
			.update(Buffer.from([1, 2, 3]))
			.digest('hex');
		const manifest = ['# Generated by shasum -a 256', '', `${expectedHash}  a.png`, ''].join('\n');
		await writeFile(join(tempDir, 'a.sha256'), manifest);
		const result = await verifyFixtureIntegrity(join(tempDir, 'a.sha256'));
		expect(result.ok).toBe(true);
	});

	it('reports multiple failures across multiple files', async () => {
		await writeFile(join(tempDir, 'good.png'), Buffer.from([1, 2, 3]));
		await writeFile(join(tempDir, 'tampered.png'), Buffer.from([9, 9, 9]));
		const goodHash = createHash('sha256')
			.update(Buffer.from([1, 2, 3]))
			.digest('hex');
		const wrongHash = 'a'.repeat(64);
		const manifest = [
			`${goodHash}  good.png`,
			`${wrongHash}  tampered.png`,
			`${wrongHash}  missing.png`,
		].join('\n');
		await writeFile(join(tempDir, 'a.sha256'), manifest);
		const result = await verifyFixtureIntegrity(join(tempDir, 'a.sha256'));
		expect(result.ok).toBe(false);
		expect(result.failures).toHaveLength(2);
		const reasons = result.failures.map((f) => f.reason).sort();
		expect(reasons).toEqual(['mismatch', 'missing']);
		const paths = result.failures.map((f) => f.path).sort();
		expect(paths).toEqual(['missing.png', 'tampered.png']);
	});
});
